spring.application.name=JobSerivce
server.port=8081

spring.cloud.config.enabled=false
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.datasource.url=jdbc:h2:mem:jobdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

job-service.url=http://localhost:8081
company-service.url=http://localhost:8082
review-service.url=http://localhost:8083

spring.cloud.openfeign.circuitbreaker.enabled=false
management.tracing.enabled=false
