spring.application.name=job-services

resilience4j.retry.instances.companyBreaker.max-attempts=5
resilience4j.retry.instances.companyBreaker.wait-duration=2s

spring.config.import=configserver:http://localhost:8080
