job-service.url=http://job:8081
company-service.url=http://company:8082
review-service.url=http://review:8083


spring.application.name=job-services

server.port=8081
spring.datasource.url=jdbc:postgresql://postgres:5432/job
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.openfeign.circuitbreaker.enabled=true

#Resilience4j
resilience4j.retry.instances.companyBreaker.max-attempts=5
resilience4j.retry.instances.companyBreaker.wait-duration=2s

resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.companyBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.companyBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.companyBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.companyBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.companyBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.companyBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-type=count_based

resilience4j.ratelimiter.instances.companyBreaker.limit-refresh-period=4

resilience4j.ratelimiter.instances.companyBreaker.limit-for-period=2
resilience4j.ratelimiter.instances.companyBreaker.timeout-duration=0

#CircuitBeaker
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents

#zipkin
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

#Config Server
spring.config.import=configserver:http://configserver:8080
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.multiplier=1.5
