spring.application.name=gateway

server.port=8084


eureka.client.service-url.defaultZone=http://localhost:5761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

management.tracing.sampling.probability=1.0

spring.cloud.gateway.server.webmvc.routes[0].id=CompanyService
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/companies/**

spring.cloud.gateway.server.webmvc.routes[1].id=JobSerivce
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.server.webmvc.routes[2].id=ReviewServices
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/reviews/**
