job-service.url=http://job:8081
company-service.url=http://company:8082
review-service.url=http://review:8083



spring.application.name=ReviewServices

server.port=8083
spring.datasource.url=jdbc:postgresql://postgres:5432/review
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://servicereg:5761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


management.tracing.sampling.probability=1.0
spring.config.import=configserver:http://ConfigServer:8080