spring.application.name=ReviewServices
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/review
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://localhost:5761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.tracing.sampling.probability=1.0