spring.application.name=CompanyService
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:5761/eureka/


management.tracing.sampling.probability=1.0


