job-service.url=http://job:8081
company-service.url=http://company:8082
review-service.url=http://review:8083


spring.application.name=CompanyService
server.port=8082
spring.datasource.url=jdbc:postgresql://postgres:5432/company
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


#Zipkin
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.config.import=configserver:http://configserver:8080




